environment:
    rustversion: 1.55.0
    matrix:
            - platform: x86_64
              rusthash: 1608A48C5C20A72CCF7037EB4B1A860B1DC51662F8BED42DF160779A9873B40B
            - platform: i686
              rusthash: A24EBB5D11280BC7A17DF7D8FBC2B73280AB5501AE3DBE997AC208A45A1BE072
install:
# Need Mingw to build C bits
- SET PATH=%PATH%;C:\MinGW\bin
- ps: Start-FileDownload https://static.rust-lang.org/dist/rust-$env:RUSTVERSION-$env:PLATFORM-pc-windows-msvc.msi -FileName rust.msi
- ps: |
        $h = (Get-FileHash rust.msi).Hash
        if ($h -ne $env:rusthash) {
                throw "Hash mismatch while downloading Rust"
        }
- msiexec /passive /i rust.msi ADDLOCAL=Rustc,Cargo,Std INSTALLDIR=C:\Rust
- start /wait msiexec /i rust.msi INSTALLDIR="C:\Program Files\Rust" /quiet /qn /norestart /log install.log
- SET PATH=%PATH%;C:\Rust\bin
- rustc -vV
- cargo -V
- set RUST_BACKTRACE=1
matrix:
  fast_finish: true
build_script:
- contrib\appveyor-build.bat
after_build:
- contrib\appveyor-after-build.bat
test_script:
- contrib\appveyor-test.bat
artifacts:
- path: '*.zip'
deploy:
  - provider: GitHub
    description: Automated builds (Appveyor)
    release: $(appveyor_repo_tag_name)
    auth_token:
      secure: Hx2tU6GZPZNB6qGjHcIqa1tEm8fVGXZUVfXyjboVrPcmA9OWMTXhLxayDzMMl3kD
    artifact: /.*\.zip/ 
    prerelease: false
    on:
      appveyor_repo_tag: true
